# Generated by Django 5.0.4 on 2025-07-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_invoice_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
